coba-jadwal/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\dashboardController;
use App\Http\Controllers\kategoriController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\AsmaulController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\IklanController;
use App\Http\Controllers\JadwalShalatController;
use App\Http\Controllers\SholatController;
use App\Http\Controllers\userController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Tampilan awal 
route::get('/', [FrontendController::class, 'index'])->name('index');

route::get('detail-artikel/{slug}', [FrontendController::class, 'detail'])->name('detail-artikel');

// Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::get('/detail-page', [FrontendController::class, 'article'])->name('detail-page');

Route::get('/detail-page/{category}', [FrontendController::class, 'categories'])->name('detail-cat');

Route::get('/notfound', [FrontendController::class, 'notfound'])->name('notfound');

Route::get('/kategori/{slug}', [FrontendController::class, 'kategori'])->name('kategori');

Route::get('/asmaul-husna', [AsmaulController::class, 'index'])->name('asmaul-husna.index');

//route untuk menu user di admin
Route::get('/user', [userController::class, 'index'])->name('user');
Route::get('/user/create', [userController::class, 'create'])->name('user.create');
Route::post('/user', [userController::class, 'store'])->name('user.store');
Route::delete('/user/{id}', [userController::class, 'destroy'])->name('user.destroy');
//end route

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    // Rute-rute yang memerlukan otentikasi
    // ...
    // start route untuk di resoursce admin
    Route::get('/dashboard', [dashboardController::class, 'index'])->name('dashboard');
    Route::resource('kategori', kategoriController::class);
    Route::resource('artikel', ArtikelController::class);
    Route::resource('slide', SlideController::class);
    Route::resource('iklan', IklanController::class);
    // end route

    //start route calender jadwal shalat di backend
    Route::get('Jadwal', [SholatController::class, 'index'])->name('Jadwal.index');
    Route::post('/getKabupatenSholat', [SholatController::class, 'getKabupaten'])->name('getKabupatenSholat');
    //end route calender jadwal shalat
});

//start route calender jadwal shalat di frontend
Route::get('/jadwalshalat', [JadwalShalatController::class, 'index'])->name('jadwalshalat.index');
Route::post('/getKabupatenJadwalShalat', [JadwalShalatController::class, 'getKabupaten'])->name('getKabupatenJadwalShalat');
//end route calender jadwal shalat



//route untuk file manage di dalam views-back-artikel-(create dan edit)
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

coba-jadwal/app/Models/Artikel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Artikel extends Model
{
    use HasFactory;

    protected $table = 'artikel';

    protected $fillable = [
        'judul', 'slug', 'kategori_id', 'user_id', 'gambar_artikel', 'is_active', 'views', 'body'
    ];

    protected $hidden = [];


    public function kategori()
    {
        return $this->belongsTo(Kategori::class, 'kategori_id', 'id');
    }

    public function users()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

coba-jadwal/app/Http/Controllers/ArtikelController.php
<?php

namespace App\Http\Controllers;

use App\Models\Artikel;
use App\Models\Kategori;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use RealRashid\SweetAlert\Facades\Alert;

class ArtikelController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        // Mendapatkan role dari user yang sedang masuk
        $level = Auth::user()->level;

        // Jika user adalah admin, tampilkan semua artikel dari semua penulis
        if ($level == 'admin') {
            $artikel = Artikel::all();
        } else {
            // Jika user adalah penulis, tampilkan artikel yang ditulis oleh penulis tersebut
            $penulisId = Auth::user()->id;
            $artikel = Artikel::where('user_id', $penulisId)->orWhereDoesntHave('users')->get();
        }

        return view('back.artikel.index', [
            'artikel' => $artikel
        ]);
    }


    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $kategori = Kategori::all();

        return view('back.artikel.create', compact('kategori'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // Validasi form
        $this->validate($request, [
            'judul' => 'required',
            'gambar_artikel' => 'required',
            'is_active' => 'required',
        ]);


        $data = [
            'judul' => $request->judul,
            'slug' => Str::slug($request->judul),
            'body' => $request->body,
            'kategori_id' => $request->kategori_id,
            'gambar_artikel' => $request->gambar_artikel,
            'is_active' => $request->is_active,
            'user_id' => Auth::id(),
            'views' => 0,
        ];


        // Menyimpan data artikel ke database
        Artikel::create($data);

        // Menampilkan pesan sukses dan mengarahkan kembali ke halaman index
        Alert::success('Success', 'Data berhasil ditambahkan');
        return redirect()->route('artikel.index');
    }



    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $artikel = Artikel::find($id);
        $kategori = Kategori::all();


        return view('back.artikel.edit', [
            'artikel' => $artikel,
            'kategori' => $kategori
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $this->validate($request, [
            'judul' => 'required',
            'gambar_artikel' => 'required',
        ]);

        $artikel = Artikel::find($id);

        // Update data artikel
        $artikel->update([
            'judul' => $request->judul,
            'body' => $request->body,
            'slug' => Str::slug($request->judul),
            'kategori_id' => $request->kategori_id,
            'gambar_artikel' => $request->gambar_artikel,
            'is_active' => $request->is_active,
            'user_id' => Auth::id(),
        ]);

        Alert::warning('Success', 'Data berhasil diupdate');
        return redirect()->route('artikel.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $artikel = Artikel::find($id);

        Storage::delete($artikel->gambar_artikel);

        $artikel->delete();


        Alert::success('Success', 'Data berhasil dihapus');
        return redirect()->route('artikel.index');
    }
}

coba-jadwal/resources/views/back/artikel/create.blade.php
@extends('layouts.default')

@section('content')

<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <!-- Content inside panel-header, if any -->
        </div>
    </div>
</div>

<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-header">
                    <div class="card-head-row">
                        <div class="card-title">Form Artikel</div>
                        <a href="{{ route('artikel.index') }}" class="btn btn-warning ml-auto">Back</a>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('artikel.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="artikel">Judul Artikel</label>
                            <input type="text" name="judul" class="form-control" id="text" placeholder="Masukkan judul artikel">
                        </div>
                        <div class="form-group">
                            <label for="body">Body</label>
                            <textarea name="body" id="editor" class="form-control"> </textarea>
                        </div>
                        <div class="form-group">
                            <label for="kategori">Kategori</label>
                            <select name="kategori_id" class="form-control">
                                @foreach ($kategori as $row)
                                <option value="{{ $row->id }}">{{ $row->nama_kategori }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="gambar">Gambar artikel</label>
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-light">
                                        <i class="fa fa-picture-o"></i>pilih gambar
                                    </a>
                                </span>
                                <input id="thumbnail" class="form-control" type="text" name="gambar_artikel">
                            </div>
                        </div>
                        <img id="holder" style="margin-top:15px;max-height:100px;">
                        <div class="form-group">
                            <label for="status">Status</label>
                            <select name="is_active" class="form-control">
                                <option value="1">Publish</option>
                                <option value="0">Draft</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Save</button>
                            <button class="btn btn-danger" type="reset">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection
@section('script')
    <script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>

    <script>
        $(document).ready(function () {
            // Laravel File Manager script
            $('#lfm').filemanager('image', {
                prefix: '/laravel-filemanager'
            });

            // CKEditor script
            var options = {
                filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
                filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
                filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
                filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token=',
            };

            CKEDITOR.replace('editor', options);
        });
    </script>
@endsection

coba-jadwal/resources/views/back/artikel/edit.blade.php
@extends('layouts.default')

@section('content')

<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">

        </div>
    </div>
</div>
<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-header">
                    <div class="card-head-row">
                        <div class="card-title">Edit Artikel {{ $artikel->judul }}</div>
                        <a href="{{ route ('artikel.index') }}" class="btn btn-warning ml-auto">Back</a>
                    </div>
                </div>
                <div class="card-body">
                    <form method="post" action="{{ route('artikel.update',$artikel->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="artikel">Judul Artikel</label>
                            <input type="text" name="judul" class="form-control" id="text" value="{{ $artikel->judul }}">
                        </div>
                        <div class="form-group">
                            <label for="body">Body</label>
                            <textarea name="body" id="editor" class="form-control">{{ $artikel->body}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="kategori">Kategori </label>

                            <select name="kategori_id" class="form-control">
                                @foreach ($kategori as $row)
                                @if ($row->id == $artikel->kategori_id)
                                <option value={{ $row->id }} selected='selected'>{{ $row->nama_kategori }}</option>
                                @else
                                <option value="{{ $row->id }}">
                                    {{ $row->nama_kategori }}
                                </option>
                                @endif


                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="status">Status </label>
                            <select name="is_active" class="form-control">
                                <option value="1" {{ $artikel->is_active ==  '1' ? 'selected' : '' }}>Publish</option>
                                <option value="0" {{ $artikel->is_active ==  '0' ? 'selected' : '' }}>Draft</option>
                            </select>
                        </div>


                        <!-- Form create/edit -->
                        <div class="form-group">
                            <label for="gambar">Gambar artikel</label>
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-light">
                                        <i class="fa fa-picture-o"></i>Pilih gambar
                                    </a>
                                </span>
                                <input id="thumbnail" class="form-control" type="text" name="gambar_artikel" value="{{ asset($artikel->gambar_artikel) }}">
                            </div>
                        </div>
                        <img id="holder" style="margin-top:15px;max-height:100px;">

                        <!-- Logika untuk menentukan apakah gambar ada atau tidak di database -->
                        @if ($artikel->gambar_artikel)
                        <div class="form-group">
                            <label for="existing-image">Gambar saat ini</label>
                            <img src="{{ asset($artikel->gambar_artikel) }}" alt="Existing Image" style="max-height: 100px;">
                        </div>
                        @endif
                        
                        <div class="form-group">
                            <button class="btn btn-primary " type="submit">Save</button>
                            <button class="btn btn-danger " type="reset">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')
<script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>
<script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>

<script>
    $(document).ready(function() {
        // Laravel File Manager script
        $('#lfm').filemanager('image', {
            prefix: '/laravel-filemanager'
        });

        // CKEditor script
        var options = {
            filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
            filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
            filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
            filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token=',
        };

        CKEDITOR.replace('editor', options);
    });
</script>
@endsection

coba-jadwal/resources/views/back/artikel/index.blade.php
@extends('layouts.default')

@section('content')

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>
				<h2 class="text-white pb-2 fw-bold">Tabel artikel</h2>
				<h5 class="text-white op-7 mb-2">Halaman untuk {{ Auth::user()->level }}</h5>
			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>
<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-header">
                    <div class="card-head-row">
                        <div class="card-title">Data Artikel</div>
                        <a href="{{ route ('artikel.create') }}" class="btn btn-primary ml-auto"> <i class="fas fa-plus"></i> Tambah artikel</a>
                    </div>
                </div>
                <div class="card-body">
                    @if (Session::has('success'))
                    <div class="alert alert-primary">
                        {{ Session('success') }}
                    </div>
                    @endif
                    <div class="table-responsive">
                        <table id="example1" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama Artikel</th>
                                    <th>Slug</th>
                                    <th>Kategori</th>
                                    <th>Author</th>
                                    <th>status</th>
                                    <th>Gambar</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($artikel as $key => $row)
                                    <tr>
                                        <td>{{ $key + 1 }}</td>
                                        <td>{{ $row->judul }}</td>
                                        <td>{{ $row->slug }}</td>
                                        <td>{{ $row->kategori ? $row->kategori->nama_kategori : 'N/A' }}</td>
                                        <td>{{ $row->users ? $row->users->name : 'not available' }}</td>
                                        <!-- Periksa apakah relasi pengguna ada sebelum mengakses propertinya -->
                                        <td>
                                            @if ($row->is_active == '1')
                                                Active
                                            @else
                                                Draft
                                            @endif
                                        </td>
                                        <td><img src="{{ asset($row->gambar_artikel) }}" alt="" width="150"></td>
                                        <td>
                                            <a href="{{ route('artikel.edit', $row->id) }}" class="btn btn-warning btn-sm">
                                                <i class="fas fa-pen"></i>
                                            </a>
                                            <form action="{{ route('artikel.destroy', $row->id) }}" method="POST" class="d-inline">
                                                @csrf
                                                @method('delete')
                                                <button class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="8" class="text-center">Data Masih Kosong</td>
                                    </tr>
                                @endforelse
                            </tbody>                            
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection