coba-jadwal/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\dashboardController;
use App\Http\Controllers\kategoriController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\AsmaulController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\IklanController;
use App\Http\Controllers\JadwalShalatController;
use App\Http\Controllers\SholatController;
use App\Http\Controllers\userController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Tampilan awal 
route::get('/', [FrontendController::class, 'index'])->name('index');

route::get('detail-artikel/{slug}', [FrontendController::class, 'detail'])->name('detail-artikel');

// Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::get('/detail-page', [FrontendController::class, 'article'])->name('detail-page');

Route::get('/detail-page/{category}', [FrontendController::class, 'categories'])->name('detail-cat');

Route::get('/notfound', [FrontendController::class, 'notfound'])->name('notfound');

Route::get('/kategori/{slug}', [FrontendController::class, 'kategori'])->name('kategori');

Route::get('/asmaul-husna', [AsmaulController::class, 'index'])->name('asmaul-husna.index');

//route untuk menu user di admin
Route::get('/user', [userController::class, 'index'])->name('user');
Route::get('/user/create', [userController::class, 'create'])->name('user.create');
Route::post('/user', [userController::class, 'store'])->name('user.store');
Route::delete('/user/{id}', [userController::class, 'destroy'])->name('user.destroy');
//end route

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    // Rute-rute yang memerlukan otentikasi
    // ...
    // start route untuk di resoursce admin
    Route::get('/dashboard', [dashboardController::class, 'index'])->name('dashboard');
    Route::resource('kategori', kategoriController::class);
    Route::resource('artikel', ArtikelController::class);
    Route::resource('slide', SlideController::class);
    Route::resource('iklan', IklanController::class);
    // end route

    //start route calender jadwal shalat di backend
    Route::get('Jadwal', [SholatController::class, 'index'])->name('Jadwal.index');
    Route::post('/getKabupatenSholat', [SholatController::class, 'getKabupaten'])->name('getKabupatenSholat');
    //end route calender jadwal shalat
});

//start route calender jadwal shalat di frontend
Route::get('/jadwalshalat', [JadwalShalatController::class, 'index'])->name('jadwalshalat.index');
Route::post('/getKabupatenJadwalShalat', [JadwalShalatController::class, 'getKabupaten'])->name('getKabupatenJadwalShalat');
//end route calender jadwal shalat



//route untuk file manage di dalam views-back-artikel-(create dan edit)
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

coba-jadwal/resources/views/includes/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="https://www.themekita.com">
                        ThemeKita
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Help
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Licenses
                    </a>
                </li>
            </ul>
        </nav>
        <div class="copyright ml-auto">
            2023, made with <i class="fa fa-heart skull text-danger"></i> by <a href="#">by Group 4</a>
        </div>				
    </div>
</footer>

coba-jadwal/resources/views/includes/header.blade.php
<div class="main-header">
    <!-- Logo Header -->
    <div class="logo-header" data-background-color="blue">
        <a href="#" class="logo" id="logo-click">
            <img src="{{ asset('back/img/12logo.png') }}" alt="navbar brand" class="navbar-brand">
        </a>
        <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="#collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
                <i class="icon-menu"></i>
            </span>
        </button>
        <button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
        <div class="nav-toggle">
            <button class="btn btn-toggle toggle-sidebar">
                <i class="icon-menu"></i>
            </button>
        </div>
    </div>

    <!-- End Logo Header -->

    <!-- Navbar Header -->
    <nav class="navbar navbar-header navbar-expand-lg" data-background-color="blue2">

        <div class="container-fluid">
            {{-- <div class="collapse" id="search-nav">
                <form class="navbar-left navbar-form nav-search mr-md-3">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <button type="submit" class="btn btn-search pr-1">
                                <i class="fa fa-search search-icon"></i>
                            </button>
                        </div>
                        <input type="text" placeholder="Search ..." class="form-control">
                    </div>
                </form>
            </div> --}}

        </div>
    </nav>
    <!-- End Navbar -->
</div>

coba-jadwal/resources/views/includes/js.blade.php
<!--   Core JS Files   -->
<script src="{{ asset('back/js/core/jquery.3.2.1.min.js')}}"></script>
<script src="{{ asset('back/js/core/popper.min.js')}}"></script>
<script src="{{ asset('back/js/core/bootstrap.min.js')}}"></script>

<!-- jQuery UI -->
<script src="{{ asset('back/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js')}}"></script>
<script src="{{ asset('back/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js')}}"></script>

<!-- jQuery Scrollbar -->
<script src="{{ asset('back/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js')}}"></script>


<!-- Chart JS -->
<script src="{{ asset('back/js/plugin/chart.js/chart.min.js')}}"></script>

<!-- jQuery Sparkline -->
<script src="{{ asset('back/js/plugin/jquery.sparkline/jquery.sparkline.min.js')}}"></script>

<!-- Chart Circle -->
<script src="{{ asset('back/js/plugin/chart-circle/circles.min.js')}}"></script>

<!-- Datatables -->
<script src="{{ asset('back/js/plugin/datatables/datatables.min.js')}}"></script>
<script>
    $(function () {
    $("#example1").DataTable();
    });
</script>

@yield('script')


<!-- Bootstrap Notify -->
{{-- <script src="{{ asset('back/js/plugin/bootstrap-notify/bootstrap-notify.min.js')}}"></script> --}}

<!-- jQuery Vector Maps -->
<script src="{{ asset('back/js/plugin/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{ asset('back/js/plugin/jqvmap/maps/jquery.vmap.world.js')}}"></script>

<!-- Sweet Alert -->
<script src="{{ asset('back/js/plugin/sweetalert/sweetalert.min.js')}}"></script>

{{-- Atlantis JS  --}}
<script src="{{ asset('back/js/atlantis.min.js')}}"></script>
{{-- 
 Atlantis DEMO methods, don't include it in your project!  --}}
<script src="{{ asset('back/js/setting-demo.js')}}"></script>
<script src="{{ asset('back/js/demo.js')}}"></script>
<script>
    Circles.create({
        id:'circles-1',
        radius:45,
        value:60, 
        maxValue:100,
        width:7,
        text: 5,
        colors:['#f1f1f1', '#FF9E27'],
        duration:400,
        wrpClass:'circles-wrp',
        textClass:'circles-text',
        styleWrapper:true,
        styleText:true
    })

    Circles.create({
        id:'circles-2',
        radius:45,
        value:70,
        maxValue:100,
        width:7,
        text: 36,
        colors:['#f1f1f1', '#2BB930'],
        duration:400,
        wrpClass:'circles-wrp',
        textClass:'circles-text',
        styleWrapper:true,
        styleText:true
    })

    Circles.create({
        id:'circles-3',
        radius:45,
        value:40,
        maxValue:100,
        width:7,
        text: 12,
        colors:['#f1f1f1', '#F25961'],
        duration:400,
        wrpClass:'circles-wrp',
        textClass:'circles-text',
        styleWrapper:true,
        styleText:true
    })

    var totalIncomeChart = document.getElementById('totalIncomeChart').getContext('2d');

    var mytotalIncomeChart = new Chart(totalIncomeChart, {
        type: 'bar',
        data: {
            labels: ["S", "M", "T", "W", "T", "F", "S", "S", "M", "T"],
            datasets : [{
                label: "Total Income",
                {{ asset('backgroundColor: '#ff9e27',
                borderColor: 'rgb(23, 125, 255)',
                data: [6, 4, 9, 5, 4, 6, 4, 3, 8, 10],
            }],
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            legend: {
                display: false,
            },
            scales: {
                yAxes: [{
                    ticks: {
                        display: false //this will remove only the label
                    },
                    gridLines : {
                        drawBorder: false,
                        display : false
                    }
                }],
                xAxes : [ {
                    gridLines : {
                        drawBorder: false,
                        display : false
                    }
                }]
            },
        }
    });

    $('#lineChart').sparkline([105,103,123,100,95,105,115], {
        type: 'line',
        height: '70',
        width: '100%',
        lineWidth: '2',
        lineColor: '#ffa534',
        fillColor: 'rgba(255, 165, 52, .14)'
    }); 
</script>

coba-jadwal/resources/views/includes/sidebar.blade.php
<div class="sidebar sidebar-style-2">
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
        <div class="sidebar-content">
            <div class="user">
                <div class="avatar-sm float-left mr-2">
                    <img src="{{  asset('back/img/profile.jpg')}}" alt="..." class="avatar-img rounded-circle">
                </div>
                <div class="info">
                    <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                        <span>
                            {{ Auth::user()->name }}
                            <span class="user-level">{{ Auth::user()->level }}</span>

                        </span>
                    </a>
                    <div class="clearfix"></div>

                    {{-- <div class="collapse in" id="collapseExample">
                        <ul class="nav">
                            <li>
                                <a href="#profile">
                                    <span class="link-collapse">My Profile</span>
                                </a>
                            </li>
                        </ul>
                    </div> --}}
                </div>
            </div>

            <ul class="nav nav-primary">
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Halaman utama {{ Auth::user()->level }}</h4>
                </li>

                <li class="nav-item">
                    <a href="/dashboard">
                        <i class="fa fa-pause"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Master Data</h4>
                </li>


                <li class="nav-item">
                    <a href="{{ route('artikel.index') }}">
                        <i class="fas fa-book"></i>
                        <p>Artikel</p>
                    </a>
                </li>

               
                <li class="nav-item">
                    <a href="{{ route('slide.index') }}">
                        <i class="fas fa-image"></i>
                        <p>Slide Banner</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('iklan.index') }}">
                        <i class="fas fa-link  "></i>
                        <p>Iklan</p>
                    </a>
                </li>
             
                @if (Auth::user()->level == 'admin')
                <li class="nav-item">
                    <a href="{{ route('kategori.index') }}">
                        <i class="fas fa-desktop"></i>
                        <p>Kategori</p>
                    </a>
                </li>

                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Master Jadwal</h4>
                </li>


                <li class="nav-item">
                    <a href="{{ route('Jadwal.index') }}">
                        <i class="fas fa-archway"></i>
                        <p>Jadwal-shalat</p>
                    </a>
                </li>

                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Sign-in</h4>
                </li>

                <li class="nav-item">
                    <a href="{{ route('user') }}">
                        <i class="fas fa-users"></i>
                        <p>Users</p>
                    </a>
                </li>

                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Back</h4>
                </li>

                @endif
                <li class="nav-item">
                    <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        <i class="fas fa-undo"></i>
                        <p>{{ __('Logout') }}</p>
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
            </ul>
        </div>
    </div>
</div>