coba-jadwal/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\dashboardController;
use App\Http\Controllers\kategoriController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\AsmaulController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\IklanController;
use App\Http\Controllers\JadwalShalatController;
use App\Http\Controllers\SholatController;
use App\Http\Controllers\userController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Tampilan awal 
route::get('/', [FrontendController::class, 'index'])->name('index');

route::get('detail-artikel/{slug}', [FrontendController::class, 'detail'])->name('detail-artikel');

// Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::get('/detail-page', [FrontendController::class, 'article'])->name('detail-page');

Route::get('/detail-page/{category}', [FrontendController::class, 'categories'])->name('detail-cat');

Route::get('/notfound', [FrontendController::class, 'notfound'])->name('notfound');

Route::get('/kategori/{slug}', [FrontendController::class, 'kategori'])->name('kategori');

Route::get('/asmaul-husna', [AsmaulController::class, 'index'])->name('asmaul-husna.index');

//route untuk menu user di admin
Route::get('/user', [userController::class, 'index'])->name('user');
Route::get('/user/create', [userController::class, 'create'])->name('user.create');
Route::post('/user', [userController::class, 'store'])->name('user.store');
Route::delete('/user/{id}', [userController::class, 'destroy'])->name('user.destroy');
//end route

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    // Rute-rute yang memerlukan otentikasi
    // ...
    // start route untuk di resoursce admin
    Route::get('/dashboard', [dashboardController::class, 'index'])->name('dashboard');
    Route::resource('kategori', kategoriController::class);
    Route::resource('artikel', ArtikelController::class);
    Route::resource('slide', SlideController::class);
    Route::resource('iklan', IklanController::class);
    // end route

    //start route calender jadwal shalat di backend
    Route::get('Jadwal', [SholatController::class, 'index'])->name('Jadwal.index');
    Route::post('/getKabupatenSholat', [SholatController::class, 'getKabupaten'])->name('getKabupatenSholat');
    //end route calender jadwal shalat
});

//start route calender jadwal shalat di frontend
Route::get('/jadwalshalat', [JadwalShalatController::class, 'index'])->name('jadwalshalat.index');
Route::post('/getKabupatenJadwalShalat', [JadwalShalatController::class, 'getKabupaten'])->name('getKabupatenJadwalShalat');
//end route calender jadwal shalat



//route untuk file manage di dalam views-back-artikel-(create dan edit)
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

coba-jadwal/app/Models/kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class kategori extends Model
{
    use HasFactory;

    protected $table = 'kategori';

    protected $fillable = [
        'nama_kategori', 'slug'
    ];

    protected $hidden = [];

    public function artikel()
    {
        return $this->hasMany(Artikel::class, 'kategori_id');
    }
}

coba-jadwal/app/Http/Controllers/kategoriController.php
<?php

namespace App\Http\Controllers;

use App\Models\kategori;
use Illuminate\Http\Request;
use Illuminate\support\Str;
use RealRashid\SweetAlert\Facades\Alert;

class kategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $kategori = kategori::all();
        return view('back.kategori.index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resosurce.
     */
    public function create()
    {
        return view('back.kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_kategori' => 'required|min:4',
        ]);

        $kategori = kategori::create([
            'nama_kategori' => $request->nama_kategori,
            'slug' => Str::slug($request->nama_kategori)
        ]);

        Alert::success('Success', 'Data berhasil ditambahkan');
        return redirect()->route('kategori.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $kategori = kategori::find($id);

        return view('back.kategori.edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $data = $request->all();
        $data['slug'] = Str::slug($request->nama_kategori);

        $kategori = kategori::findOrfail($id);
        $kategori->update($data);

        Alert::info('Success', 'Data berhasil diupdate');
        return redirect()->route('kategori.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $kategori = kategori::find($id);

        $kategori->delete();

        Alert::error('Success', 'Data berhasil dihapus');
        return redirect()->route('kategori.index');
    }
}

coba-jadwal/resources/views/back/kategori/create.blade.php
@extends('layouts.default')

@section('content')
    
<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
	
	</div>
</div>

<div class="page-inner mt--5">
	<div class="row">
		<div class="col-md-12">
			<div class="card full-height">
				<div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Tambah Kategori</div>
                        <a href="{{ route('kategori.index') }}" class="btn btn-warning sm ml-auto"><i class="fas fa-undo"></i>back</a>
					</div>
				</div>
				<div class="card-body">
                    <form method="post" action="{{ route('kategori.store') }}">
                        @csrf
                    <div class="form-group">
                        <label for="kategori">Nama kategori</label>
                        <input type="text" name="nama_kategori" class="form-control" id="text" placeholder="Enter kategori">
                    </div>

                    <div class="form-group">
                    <button class="btn btn-primary btn-sm" type="submit">save</button>
                    </div>
                    </form>

				</div>
			</div>
		</div>
	</div>
</div>

@endsection

coba-jadwal/resources/views/back/kategori/edit.blade.php
@extends('layouts.default')

@section('content')
    
<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
	
	</div>
</div>

<div class="page-inner mt--5">
	<div class="row">
		<div class="col-md-12">
			<div class="card full-height">
				<div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Edit kategori <i>{{ $kategori->nama_kategori }}</i></div>
                        <a href="{{ route('kategori.index') }}" class="btn btn-warning sm ml-auto"><i class="fas fa-undo"></i>back</a>
					</div>
				</div>
				<div class="card-body">
                    <form method="post" action="{{ route('kategori.update' , $kategori->id) }}">
                        @csrf
                        @method('put')
                    <div class="form-group">
                        <label for="kategori">Nama kategori</label>
                        <input type="text" name="nama_kategori" value="{{ $kategori->nama_kategori }}" class="form-control" id="text" placeholder="Enter kategori">
                    </div>
                    
                    <div class="form-group">
                    <button class="btn btn-primary btn-sm" type="submit">save</button>
                    </div>
                    </form>

				</div>
			</div>
		</div>
	</div>
</div>

@endsection

coba-jadwal/resources/views/back/kategori/index.blade.php
@extends('layouts.default')

@section('content')
    
<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>
				<h2 class="text-white pb-2 fw-bold">Tabel Kategori</h2>
				<h5 class="text-white op-7 mb-2"></h5>
			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
	<div class="row">
		<div class="col-md-12">
			<div class="card full-height">
				<div class="card-header">
					<div class="card-head-row">
						<div class="card-title">DataKategori</div>
                        <a href="{{ route('kategori.create') }}" class="btn btn-primary sm ml-auto"><i class="fas fa-plus"></i> Tambah Kategori</a>
					</div>
				</div>
				<div class="card-body">

                    @if(Session::has('success'))
                    <div class="alert alert-primary">
                        {{ Session('success') }}
                    </div>

                    @endif

					<div class="table-responsive">
					<table id="example1" class="table table-bordered">
                        <thead>
                            <tr>
                                <th> No</th>
                                <th> Nama kategori</th>
                                <th> Slug</th>
                                <th> action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @forelse ($kategori as $key => $row)

                              <tr>
                                <td>{{ $key + 1 }}</td>
                                <td>{{ $row->nama_kategori }}</td>
                                <td>{{ $row->slug }}</td>
                                <td>
                                    <a href="{{ route('kategori.edit', $row->id) }}" class="btn btn-warning btn-sm" style="margin:auto"><i class="fas fa-pen"></i></a>
                                    
                                    <form action="{{ route('kategori.destroy', $row->id) }}" method="post" class="d-inline" style="margin:auto">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger btn-sm">
                                            <i class="fas fa-trash"></i>
                                    </form>

                                </td>
                            </tr>
                            @empty

                            <tr>
                                <td>Data masih kosong</td>
                            </tr>
                                
                            @endforelse
                            
                        </tbody>
                    </table>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>
@endsection